spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:./
  security:
    user:
      name: cloudconfig
      password: AoM4jK829FW7MssBhhdBBdfTH
encrypt:
  key: FxUjrRSbAb3q9fxdUAFKZPBK2
